# see https://github.com/joshirio/symphytum-build.snapcraft.io/ for releasing on snap store
name: symphytum
version: '2.5'
summary: Easy-to-use personal database software
description: |
  Symphytum is a personal database software for everyone 
  who desires to manage and organize data in an easy and intuitive way, 
  without having to study complex database languages and software user interfaces.

icon: gui/symphytum.png
grade: stable
confinement: strict
base: core18 # based on ubuntu 18.04 LTS

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  symphytum:
    adapter: full
    command: bin/symphytum
    command-chain:
      - bin/desktop-launch
      - bin/gtk3-env-launch
    desktop: usr/share/applications/symphytum.desktop
    environment:
      DISABLE_WAYLAND: 1 # disable wayland (not ready yet), comment out this line to enable full wayland support
      #QT_QPA_PLATFORMTHEME: gtk3 # gtk-common-themes support, currently overrided by desktop-launch(`appmenu-qt5`), implement in snap launcher instead
    plugs:
      - home
      - network
      - opengl
      - removable-media
      - unity7
      - x11
      - wayland
      - gsettings # allow wayland apps access system theme settings
      - desktop
      - desktop-legacy

parts:
  launchers: # custom launcher to set QT_QPA_PLATFORMTHEME=gtk3 correctly
    source: local/launchers
    plugin: dump
    organize:
      '*': bin/
    stage:
      - -bin/README.*

  symphytum:
    source: https://github.com/giowck/symphytum.git
    source-tag: v2.5
    plugin: qmake
    qt-version: qt5
    options:
      - CONFIG+=release
    override-build: | # enable snap deployment target and set app store
      sed -i 's#bool DefinitionHolder::SNAP_LINUX = false;#bool DefinitionHolder::SNAP_LINUX = true;#' utils/definitionholder.cpp
      sed -i 's#bool DefinitionHolder::APP_STORE = false;#bool DefinitionHolder::APP_STORE = true;#' utils/definitionholder.cpp
      snapcraftctl build # call default snapcraft build
      #custom install steps (formerly known as install but now deprecated)
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp symphytum $SNAPCRAFT_PART_INSTALL/bin
      tar xzvf stuff/installers/deb/usr/share/symphytum/sync/dropbox-*.tar.gz -C stuff/installers/deb/usr/share/symphytum/sync/
      rm -v stuff/installers/deb/usr/share/symphytum/sync/dropbox-*.tar.gz
      cp -R stuff/installers/deb/usr $SNAPCRAFT_PART_INSTALL/
      sed -i 's|Icon=symphytum|Icon=${SNAP}/usr/share/pixmaps/symphytum.png|g' $SNAPCRAFT_PART_INSTALL/usr/share/applications/symphytum.desktop
    build-packages:
      - libqt5svg5-dev
    stage-packages:
      - qttranslations5-l10n
      - libqt5core5a
      - libqt5gui5
      - libqt5network5
      - libqt5sql5-sqlite
      - libqt5svg5
      - libqt5printsupport5
      - qtwayland5
      - zlib1g
      - dbus
      # for theming, font settings, cursor and to use gtk3 file chooser
      - qt5-gtk-platformtheme 
    after: [desktop-qt5]
    
  dropbox-sync:
    plugin: python
    python-version: python3
    python-packages:
      - setuptools
      - six
      - certifi
      - chardet
      - idna
      - requests
      - urllib3
      
  megacmd-sync:
    source: https://mega.nz/linux/MEGAsync/xUbuntu_18.04/amd64/megacmd-xUbuntu_18.04_amd64.deb
    plugin: dump
    stage:
      - usr/*
    stage-packages:
      - libc-ares2
      - libcrypto++6
      - libgcc1
      - libmediainfo0v5
      - libpcre3
      - libpcrecpp0v5
      - libssl1.1
      - libstdc++6
      - libzen0v5
      - zlib1g
      - apt-transport-https

  desktop-qt5: # custom define becasue no remote parts are supported when using a base (at least not on 16.04), https://github.com/ubuntu/snapcraft-desktop-helpers
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
